### PR TITLE
[ADD] Add .gitignore file follows OCA's guideline

### PR DESCRIPTION
**Pull request by novawish**
Template of `.gitignore` is in: https://github.com/OCA/maintainer-tools/blob/master/.gitignore

### CODE REVIEW

**Comment by melroy89** [comment]
@mgielissen Please merge. Also upstream to branch 11.0

**Review by melroy89 — APPROVED** [review]

**Review by IOAyman — APPROVED** [review]
LGTM 👍

**Comment by SalahAdDin** [comment]
@mgielissen Please, also the same for `11.0`.

**Review by DucTruongKomit — APPROVED** [review]
LGTM

**Pull request merged**
