### PR TITLE
[FIX] Sidebar working again. Using web_responsive from OCA.

### PR DESCRIPTION
**Pull request by carmelo-lopez**
Using some flex to make it work again. Using web_responsive from OCA repository on 13.0 branch. Not fully tested on mobile devices.

### CODE REVIEW

**Comment by mgielissen** [comment]
Thx, I will check it.

**Comment by gdgellatly** [comment]
With sidebar disabled it just leaves blank space on the right of screen

**Comment by mgielissen** [comment]
SIdebar is implemented in the latest version

**Comment by carmelo-lopez** [comment]
> SIdebar is implemented in the latest version

Tbh, your fix to the sidebar sucks, I don't think that's a good fix, my PR  works flawless. Anyways, that's your choice.

**Pull request closed without merging**
