### PR TITLE
[FIX] navbar: Set link colors in user menu for small screens

### LINKED ISSUE #34: [BUG] User menu not displaying in smaller screens
## Current behavior:

The user menu -top right corner- does is not being displayed on smaller than screens (width < 768px).

screenshot_2017-10-27_09-19-18
screenshot_2017-10-27_09-20-05

- - -
_Odoo version:_ 10.0
Theme branch: 10.0 at 9b3ee22

### PR DESCRIPTION
**Pull request by IOAyman**
Resolves #34

### CODE REVIEW

**Review by melroy89 — APPROVED** [review]

**Comment by melroy89** [comment]
@mgielissen
Please merge!

**Comment by melroy89** [comment]
Could you also also create a PR for branch 11.0? Same problem..

**Comment by veikak** [comment]
Please merge this. I'd like to upgrade but #34 is a deal-breaker.

**Comment by melroy89** [comment]
Also sync to 11.0?

**Comment by melroy89** [comment]
@IOAyman Are you willing to sync your changes to v11 branch?

**Comment by IOAyman** [comment]
@danger89, I just submitted #46.

/cc @mgielissen

**Pull request merged**
